name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    name: PHP 8.5

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: DOCKER_BUILDKIT=0 docker compose build

      - name: Run tests
        run: docker compose up --abort-on-container-exit --exit-code-from php85
